### ISSUE TITLE
The type `User` is different from the actual response

### ISSUE THREAD

**Issue by nakzyu** [figma/rest-api-spec#27]
The response from `/v1/me` differs from the User interface defined in this repository.

The current User interface is defined as follows:

```typescript
export type User = {
  /**
   * Unique stable id of the user.
   */
  id: string;

  /**
   * Name of the user.
   */
  handle: string;

  /**
   * URL link to the user's profile image.
   */
  img_url: string;
}
```

However, the actual API response includes an additional `email: string` field.

**Comment by jefflee-figma** [comment]
Thanks, we're tracking this internally (issue `1202050547272918/1204983605549039`)

**Comment by jefflee-figma** [comment]
Hi @nakzyu, the omission of `email` from the `User` type is intentional. Not all occurrences of the `User` type in the API include the email; it is only returned as the result of `GET /v1/me`. See [GetMeResponse](https://github.com/figma/rest-api-spec/blob/c81da97143759e011c24f1740ded663ff057ecd0/dist/api_types.ts#L5327-L5332).
